#
# profile file to autorun X
# used by bash and zsh

# ibus
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

list=`pgrep -U "$USER" X`
if [[ "$list" == "" ]] && [[ "$XDG_VTNR" == "1" ]]; then
    startx > ~/.xlog
fi
